### ISSUE TITLE
regex html cleanup - from bobby king

### ISSUE THREAD

**Issue by johnrbell** [JohnrBell/mta_do#13]
function formatStatusText(statusText) {
  return statusText.replace(/<(?:.|\n)_?>|&[\w]_;/gm, '');
};

**Comment by gittheking** [comment]
@JohnrBell  This should work fine in Ruby

``` ruby
def format_status_text(str)
  str.gsub(/<(?:.|\n)*?>|&[\w]*;/,"")
end
```
