### ISSUE TITLE
HACKTOBERFEST - when app is added to homescreen on iphone local links still open in safari

### ISSUE THREAD

**Issue by johnrbell** [JohnrBell/mta_do#23]
If you add this site to your homescreen, it trys to pretend to be a standalone app, icon and all. The android version of this works well- however on iphone when you click a local link (http://mtastat.us/E)
it will open safari alongside this application, rather than loading it there. 

Hope this makes sense, sorry I'm far from an iphone developer.

**Comment by jamieduke** [comment]
Let me take a look, iOS and swift are a bit anal about opening external web urls unless it's in a post or get request.
