### ISSUE TITLE
24-hour weather forecast?

### ISSUE THREAD

**Issue by 0xStarcat** [JohnrBell/mta_do#4]
If this had a 24-hour weather forecast like before it'd be the only website I visit in the morning.

**Comment by johnrbell** [comment]
recommend me an API homeboy. this ain't that easy.

**Comment by johnrbell** [comment]
and by create and issue i really meant make a pull request with your fix. :+1:

**Comment by 0xStarcat** [comment]
All over it

**Comment by johnrbell** [comment]
include rspec tests ;)
