### ISSUE TITLE
Hit API instead of XML

### ISSUE THREAD

**Issue by johnrbell** [JohnrBell/mta_do#9]
require 'sinatra'
require 'httparty'
require 'pry'

@final_hash = []

time = Time.now.to_i/60
url = "https://alert.mta.info/service_status_json/" + time.to_s
response = JSON.parse(HTTParty.get(url))
trains = response['subway']['line']
trains.each do |train| 
  train.delete("Date") 
  train.delete("Time") 
end

trains.each do |train| #split multiple trains to individual. ACE > A,C,E
  train['name'].length.times do |i|
    @final_hash.push([train['name'][i],train['status'],train['text']]) #after split, push to new array. 
  end
end

binding.pry

get '/' do 
  trains.to_s
end

**Comment by bryanmytko** [comment]
Not sure if it's worth doing this. The XML is probably faster.
